# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import safe_entry_pb2 as safe__entry__pb2


class SafeEntryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckInIndividual = channel.unary_unary(
                '/helloworld.SafeEntry/CheckInIndividual',
                request_serializer=safe__entry__pb2.CheckInIndividualRequest.SerializeToString,
                response_deserializer=safe__entry__pb2.CheckOutIndividualReply.FromString,
                )
        self.CheckInGroup = channel.unary_unary(
                '/helloworld.SafeEntry/CheckInGroup',
                request_serializer=safe__entry__pb2.CheckInGroupRequest.SerializeToString,
                response_deserializer=safe__entry__pb2.CheckOutGroupReply.FromString,
                )
        self.CheckOutIndividual = channel.unary_unary(
                '/helloworld.SafeEntry/CheckOutIndividual',
                request_serializer=safe__entry__pb2.CheckOutIndividualRequest.SerializeToString,
                response_deserializer=safe__entry__pb2.CheckOutIndividualReply.FromString,
                )
        self.CheckOutGroup = channel.unary_unary(
                '/helloworld.SafeEntry/CheckOutGroup',
                request_serializer=safe__entry__pb2.CheckOutGroupRequest.SerializeToString,
                response_deserializer=safe__entry__pb2.CheckOutGroupReply.FromString,
                )


class SafeEntryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckInIndividual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckInGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOutIndividual(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOutGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SafeEntryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckInIndividual': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInIndividual,
                    request_deserializer=safe__entry__pb2.CheckInIndividualRequest.FromString,
                    response_serializer=safe__entry__pb2.CheckOutIndividualReply.SerializeToString,
            ),
            'CheckInGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInGroup,
                    request_deserializer=safe__entry__pb2.CheckInGroupRequest.FromString,
                    response_serializer=safe__entry__pb2.CheckOutGroupReply.SerializeToString,
            ),
            'CheckOutIndividual': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOutIndividual,
                    request_deserializer=safe__entry__pb2.CheckOutIndividualRequest.FromString,
                    response_serializer=safe__entry__pb2.CheckOutIndividualReply.SerializeToString,
            ),
            'CheckOutGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOutGroup,
                    request_deserializer=safe__entry__pb2.CheckOutGroupRequest.FromString,
                    response_serializer=safe__entry__pb2.CheckOutGroupReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.SafeEntry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SafeEntry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckInIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.SafeEntry/CheckInIndividual',
            safe__entry__pb2.CheckInIndividualRequest.SerializeToString,
            safe__entry__pb2.CheckOutIndividualReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckInGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.SafeEntry/CheckInGroup',
            safe__entry__pb2.CheckInGroupRequest.SerializeToString,
            safe__entry__pb2.CheckOutGroupReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckOutIndividual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.SafeEntry/CheckOutIndividual',
            safe__entry__pb2.CheckOutIndividualRequest.SerializeToString,
            safe__entry__pb2.CheckOutIndividualReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckOutGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.SafeEntry/CheckOutGroup',
            safe__entry__pb2.CheckOutGroupRequest.SerializeToString,
            safe__entry__pb2.CheckOutGroupReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
