# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: safe_entry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10safe_entry.proto\x12\nhelloworld\"V\n\x18\x43heckInIndividualRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04nric\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\"Q\n\x13\x43heckInGroupRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\x0c\n\x04nric\x18\x02 \x03(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\"W\n\x19\x43heckOutIndividualRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04nric\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\"R\n\x14\x43heckOutGroupRequest\x12\x0c\n\x04name\x18\x01 \x03(\t\x12\x0c\n\x04nric\x18\x02 \x03(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\"(\n\x16\x43heckInIndividualReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"#\n\x11\x43heckInGroupReply\x12\x0e\n\x06status\x18\x01 \x01(\t\")\n\x17\x43heckOutIndividualReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x12\x43heckOutGroupReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf9\x02\n\tSafeEntry\x12`\n\x11\x43heckInIndividual\x12$.helloworld.CheckInIndividualRequest\x1a#.helloworld.CheckOutIndividualReply\"\x00\x12Q\n\x0c\x43heckInGroup\x12\x1f.helloworld.CheckInGroupRequest\x1a\x1e.helloworld.CheckOutGroupReply\"\x00\x12\x62\n\x12\x43heckOutIndividual\x12%.helloworld.CheckOutIndividualRequest\x1a#.helloworld.CheckOutIndividualReply\"\x00\x12S\n\rCheckOutGroup\x12 .helloworld.CheckOutGroupRequest\x1a\x1e.helloworld.CheckOutGroupReply\"\x00\x62\x06proto3')



_CHECKININDIVIDUALREQUEST = DESCRIPTOR.message_types_by_name['CheckInIndividualRequest']
_CHECKINGROUPREQUEST = DESCRIPTOR.message_types_by_name['CheckInGroupRequest']
_CHECKOUTINDIVIDUALREQUEST = DESCRIPTOR.message_types_by_name['CheckOutIndividualRequest']
_CHECKOUTGROUPREQUEST = DESCRIPTOR.message_types_by_name['CheckOutGroupRequest']
_CHECKININDIVIDUALREPLY = DESCRIPTOR.message_types_by_name['CheckInIndividualReply']
_CHECKINGROUPREPLY = DESCRIPTOR.message_types_by_name['CheckInGroupReply']
_CHECKOUTINDIVIDUALREPLY = DESCRIPTOR.message_types_by_name['CheckOutIndividualReply']
_CHECKOUTGROUPREPLY = DESCRIPTOR.message_types_by_name['CheckOutGroupReply']
CheckInIndividualRequest = _reflection.GeneratedProtocolMessageType('CheckInIndividualRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKININDIVIDUALREQUEST,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckInIndividualRequest)
  })
_sym_db.RegisterMessage(CheckInIndividualRequest)

CheckInGroupRequest = _reflection.GeneratedProtocolMessageType('CheckInGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINGROUPREQUEST,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckInGroupRequest)
  })
_sym_db.RegisterMessage(CheckInGroupRequest)

CheckOutIndividualRequest = _reflection.GeneratedProtocolMessageType('CheckOutIndividualRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTINDIVIDUALREQUEST,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckOutIndividualRequest)
  })
_sym_db.RegisterMessage(CheckOutIndividualRequest)

CheckOutGroupRequest = _reflection.GeneratedProtocolMessageType('CheckOutGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTGROUPREQUEST,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckOutGroupRequest)
  })
_sym_db.RegisterMessage(CheckOutGroupRequest)

CheckInIndividualReply = _reflection.GeneratedProtocolMessageType('CheckInIndividualReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKININDIVIDUALREPLY,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckInIndividualReply)
  })
_sym_db.RegisterMessage(CheckInIndividualReply)

CheckInGroupReply = _reflection.GeneratedProtocolMessageType('CheckInGroupReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINGROUPREPLY,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckInGroupReply)
  })
_sym_db.RegisterMessage(CheckInGroupReply)

CheckOutIndividualReply = _reflection.GeneratedProtocolMessageType('CheckOutIndividualReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTINDIVIDUALREPLY,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckOutIndividualReply)
  })
_sym_db.RegisterMessage(CheckOutIndividualReply)

CheckOutGroupReply = _reflection.GeneratedProtocolMessageType('CheckOutGroupReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTGROUPREPLY,
  '__module__' : 'safe_entry_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.CheckOutGroupReply)
  })
_sym_db.RegisterMessage(CheckOutGroupReply)

_SAFEENTRY = DESCRIPTOR.services_by_name['SafeEntry']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKININDIVIDUALREQUEST._serialized_start=32
  _CHECKININDIVIDUALREQUEST._serialized_end=118
  _CHECKINGROUPREQUEST._serialized_start=120
  _CHECKINGROUPREQUEST._serialized_end=201
  _CHECKOUTINDIVIDUALREQUEST._serialized_start=203
  _CHECKOUTINDIVIDUALREQUEST._serialized_end=290
  _CHECKOUTGROUPREQUEST._serialized_start=292
  _CHECKOUTGROUPREQUEST._serialized_end=374
  _CHECKININDIVIDUALREPLY._serialized_start=376
  _CHECKININDIVIDUALREPLY._serialized_end=416
  _CHECKINGROUPREPLY._serialized_start=418
  _CHECKINGROUPREPLY._serialized_end=453
  _CHECKOUTINDIVIDUALREPLY._serialized_start=455
  _CHECKOUTINDIVIDUALREPLY._serialized_end=496
  _CHECKOUTGROUPREPLY._serialized_start=498
  _CHECKOUTGROUPREPLY._serialized_end=534
  _SAFEENTRY._serialized_start=537
  _SAFEENTRY._serialized_end=914
# @@protoc_insertion_point(module_scope)
